[package]
name = "hyper-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# FIXME: Move this into a feature
graphrs = "0.9.0"
log = "0.4.20"
priority-queue = "2.0.3"
rand = "0.8.5"
rand_distr = "0.4.3"
simple_logger = "5.0.0"