name: Build, lint and test

on: workflow_call

permissions:
  contents: read

jobs:
  check:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install Clippy
        run: rustup component add clippy
      - name: Install Rustfmt
        run: rustup component add rustfmt
      - name: Check clippy
        run: cargo clippy --all-features --all-targets --color always -- --deny warnings

  build:
    name: Build and test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo build
        run: cargo build --release --all-features
      - name: cargo test
        run: cargo test --all-features --all-targets --benches